excluded:
    - Carthage
    - fastlane
    - support
    - Build-Phases
    - build

disabled_rules:
    - nesting
    - line_length      
    - file_length
    - identifier_name
    - force_cast
    - function_body_length
    - superfluous_disable_command
    - notification_center_detachment # [!]
    - private_action # [!]
    - private_outlet # [!]


analyzer_rules:
    - unused_import
    - unused_private_declaration

number_separator:
    minimum_length: 7

opt_in_rules:
    - empty_count
    - anyobject_protocol
    - array_init
    - attributes
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - contains_over_first_not_nil    
    - empty_string
    - empty_xctest_method
    - explicit_init
    - extension_access_modifier
    - fallthrough
    - fatal_error_message        
    - first_where
    - identical_operands
    - joined_default_parameter
    - let_var_whitespace
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - nimble_operator
    - number_separator
    - object_literal
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    - pattern_matching_keywords    
    - prohibited_super_call    
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    - redundant_nil_coalescing
    - redundant_type_annotation
    - single_test_class
    - sorted_first_last
    - sorted_imports
    - static_operator
    - unavailable_function
    - unneeded_parentheses_in_closure_argument
    - untyped_error_in_catch
    - vertical_parameter_alignment_on_call
    - yoda_condition

cyclomatic_complexity:
    ignores_case_statements: true

function_parameter_count:
    warning: 7
    error: 10

large_tuple:
    warning: 3

custom_rules:
    double_space: # from https://github.com/IBM-Swift/Package-Builder
      include: "*.swift"
      name: "Double space"
      regex: '([a-z,A-Z] \s+)'
      message: "Double space between keywords"
      match_kinds: keyword
      severity: warning

    comments_space: # from https://github.com/brandenr/swiftlintconfig
      name: "Space After Comment"
      regex: '(^ *//\w+)'
      message: "There should be a space after //"
      severity: warning

    unnecessary_type: # from https://github.com/brandenr/swiftlintconfig
      name: "Unnecessary Type"
      regex: '[ a-zA-Z0-9]*(?:let|var) [ a-zA-Z0-9]*: ([a-zA-Z0-9]*)[ ]*= \1'
      message: "Type Definition Not Needed"
      severity: warning

    # empty_line_after_super:
    #   name: "Empty Line After Super"
    #   regex: '(^ *super\.[ a-zA-Z0-9=?.\(\)\{\}:,><!]*\n *(?!(?:\}|return))\S+)'
    #   message: "There should be an empty line after super"
    #   severity: error

    # empty_first_line:
    #   name: "Empty First Line"
    #   regex: '(^[ a-zA-Z ]*(?:protocol|extension|class|struct) (?!(?:var|let))[ a-zA-Z:]*\{\n *\S+)'
    #   message: "There should be an empty line after a declaration"
    #   severity: error
